### Numpy

Numpy is a library that add the matrix as new object to python. Every dimention of a matrix in callex axis, and ob a matrix with one dimantion is an array.

We can import numpy conventionally as: ```import numpy as np```. Let's define an array:

In [1]:
import numpy as np
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

This are some useful attributes:

In [2]:
print(arr.ndim)
print(arr.shape) # 1 is implied 
print(arr.size)
print(arr.dtype)

1
(5,)
5
int32


For array we can't use the function range so:

In [3]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
a.shape

(3, 5)

In [5]:
type(a)

numpy.ndarray

In [6]:
c = np.array( [ [1,2], [3,4] ], dtype=complex )
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

Here some useful function of numpy for creating matrices:

In [7]:
print(np.zeros((2,2)))
print(np.ones((2,2)))

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]


We have seen arange but often is better use:

In [8]:
x = np.linspace( 0, 2*np.pi,3)
x

array([0.        , 3.14159265, 6.28318531])

Numpy allow as to perform some operation between arrays:

In [9]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )

In [10]:
a-b

array([20, 29, 38, 47])

In [11]:
b**2

array([0, 1, 4, 9], dtype=int32)

In [12]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [13]:
a<35

array([ True,  True, False, False])

We we mange matrice we have to care about the product, ob 2 are defined:

In [14]:
A = np.array( [[1,1],[0,1]] )
B = np.array( [[2,0],[3,4]] )
A

array([[1, 1],
       [0, 1]])

In [15]:
A*B # elemntwise product

array([[2, 0],
       [0, 4]])

In [16]:
A@B # matrix product

array([[5, 4],
       [3, 4]])

In [17]:
print(A.min())
print(A.max())
print(A.sum())

0
1
3


Remeber in Python is always raw → 0, columns → 1

In [18]:
print(A.sum(axis=1))

[2 1]


Remeber universal function are elementwise:

In [19]:
print(np.exp(A))

[[2.71828183 2.71828183]
 [1.         2.71828183]]


In [20]:
def f(x,y):
    return 10*x+y

b = np.fromfunction(f,(5,4),dtype=int) # Here (5,4) are the axis index 
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [21]:
b[3:,-2] # Remember Pyhton start counting from 0!

array([32, 42])

Some function that manipulate the shape of matrices do not change the original ones:

In [22]:
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


In [23]:
b.ravel()

array([ 0,  1,  2,  3, 10, 11, 12, 13, 20, 21, 22, 23, 30, 31, 32, 33, 40,
       41, 42, 43])

In [24]:
b.T

array([[ 0, 10, 20, 30, 40],
       [ 1, 11, 21, 31, 41],
       [ 2, 12, 22, 32, 42],
       [ 3, 13, 23, 33, 43]])

We can combine arrays in different ways:

In [25]:
a = np.floor(10*np.random.random((2,2)))
b = np.floor(10*np.random.random((2,2)))

In [26]:
np.vstack((a,b))

array([[0., 7.],
       [8., 9.],
       [5., 2.],
       [9., 2.]])

In [27]:
np.hstack((a,b))

array([[0., 7., 5., 2.],
       [8., 9., 9., 2.]])

Sometimes function that manipulate array return a new one and sometimes not. There are three cases:

* Simple assignments make no copy of arrays:

In [28]:
a = np.arange(5)
b = a            # no new object is created
b is a  

True

* Different array objects can share the same data:

In [29]:
c = a.view()
c is a

False

In [30]:
c[4] = 1234                      # a's data changes
a

array([   0,    1,    2,    3, 1234])

Slicing an array returns a view

In [31]:
 s = a
s[:] = 10           # s[:] is a view of s. Note the difference between s=10 and s[:]=10
a

array([10, 10, 10, 10, 10])

* The copy method makes a complete copy of the array and its data:

In [32]:
d = a.copy()                          # a new array object with new data is created
d is a

False

In [33]:
d[0] = 9999
a

array([10, 10, 10, 10, 10])

In [34]:
type(a)

numpy.ndarray

### Exercises

**1.** Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.

**2.** Write a NumPy program to create a 3x3 identity matrix, i.e. diagonal elements are 1, the rest are 0.

**3.** Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0

**4.** Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

**5.** Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15.

**6.** Write a NumPy program to get the values and indices of the elements that are bigger than 10 in a given array.

**7.** Write a NumPy program to split of an array of shape 4x4 it into two arrays along the second axis. 

**8.** Write a NumPy program to rearrange the dimensions of a given array.

    Sample Output:
    Original arrays:
    [[ 0 1 2 3]
    [ 4 5 6 7]
    [ 8 9 10 11]
    [12 13 14 15]
    [16 17 18 19]
    [20 21 22 23]]
    After reverse the dimensions:
    [[ 0 4 8 12 16 20]
    [ 1 5 9 13 17 21]
    [ 2 6 10 14 18 22]
    [ 3 7 11 15 19 23]]



**8.** Write a NumPy program to split an given array into multiple sub-arrays vertically (row-wise).

    Sample Output:
    Original arrays:
    [[ 0. 1. 2. 3.]
    [ 4. 5. 6. 7.]
    [ 8. 9. 10. 11.]
    [12. 13. 14. 15.]]
    Split an array into multiple sub-arrays vertically:
    [array([[0., 1., 2., 3.],
    [4., 5., 6., 7.]]), array([[ 8., 9., 10., 11.],
    [12., 13., 14., 15.]])]