**1.** Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.

In [1]:
import numpy as np
np.arange(10,22).reshape((3, 4))

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

**2.** Write a NumPy program to create a 3x3 identity matrix, i.e. diagonal elements are 1, the rest are 0.

In [2]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**3.** Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0

In [3]:
x = np.ones((10, 10))
x[1:-1, 1:-1] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


**4.** Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [4]:
np.diag([1, 2, 3, 4, 5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

**5.** Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15.

In [5]:
import numpy as np
x = np.arange(21)
x[(x >= 9) & (x <= 15)] *= -1
x

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,  -9, -10, -11, -12,
       -13, -14, -15,  16,  17,  18,  19,  20])

**6.** Write a NumPy program to get the values and indices of the elements that are bigger than 10 in a given array.

In [6]:
x = np.array([[0, 10, 20], [20, 30, 40]])
a = np.nonzero(x > 10)

for i in range(a[0].shape[0]):
    print(a[0][i],a[1][i])

0 2
1 0
1 1
1 2


**7.** Write a NumPy program to split of an array of shape 4x4 it into two arrays along the second axis. 

In [7]:
x = np.arange(16).reshape((4, 4))
print(np.hsplit(x, [2, 6]))

[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]]), array([], shape=(4, 0), dtype=int32)]


**8.** Write a NumPy program to rearrange the dimensions of a given array.

    Sample Output:
    Original arrays:
    [[ 0 1 2 3]
    [ 4 5 6 7]
    [ 8 9 10 11]
    [12 13 14 15]
    [16 17 18 19]
    [20 21 22 23]]
    After reverse the dimensions:
    [[ 0 4 8 12 16 20]
    [ 1 5 9 13 17 21]
    [ 2 6 10 14 18 22]
    [ 3 7 11 15 19 23]]



In [8]:
x = np.arange(24).reshape((6,4))
new_array = np.transpose(x)
print(new_array)

[[ 0  4  8 12 16 20]
 [ 1  5  9 13 17 21]
 [ 2  6 10 14 18 22]
 [ 3  7 11 15 19 23]]


**8.** Write a NumPy program to split an given array into multiple sub-arrays vertically (row-wise).

    Sample Output:
    Original arrays:
    [[ 0. 1. 2. 3.]
    [ 4. 5. 6. 7.]
    [ 8. 9. 10. 11.]
    [12. 13. 14. 15.]]
    Split an array into multiple sub-arrays vertically:
    [array([[0., 1., 2., 3.],
    [4., 5., 6., 7.]]), array([[ 8., 9., 10., 11.],
    [12., 13., 14., 15.]])]

In [9]:
x = np.arange(16.0).reshape(4, 4)
new_array1 =  np.vsplit(x, 2)
print(new_array1)

[array([[0., 1., 2., 3.],
       [4., 5., 6., 7.]]), array([[ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])]
